version: 2.1
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.1.3
  windows: circleci/windows@2.4.0

jobs:
  chrome:
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: Run TestCafe tests on headless Chrome
          command: npm run test:chrome:headless

  firefox:
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: Run TestCafe tests on headless Firefox
          command: npm run test:firefox:headless

  edge:
    executor:
      name: windows/default

    steps:
      - checkout
      - restore_cache:
          keys:
            - testcafe-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Installing NPM packages
          command: npm ci
      - save_cache:
          key: testcafe-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run TestCafe tests on headless Microsoft Edge
          command: npm run test:edge:headless

workflows:
  end-to-end-tests:
    jobs:
      - chrome
      - firefox:
          requires:
            - chrome
      - edge:
          requires:
            - firefox
