version: 2.1
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  chrome:
    docker:
      - image: cimg/node:12.22-browsers

    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          command: npm run test:chrome:headless

workflows:
  end-to-end-tests:
    jobs:
      - chrome
